# Generated by Django 4.2.1 on 2023-06-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Burger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("priceM", models.DecimalField(decimal_places=3, max_digits=8)),
                ("priceL", models.DecimalField(decimal_places=3, max_digits=8)),
                ("bImage", models.URLField()),
            ],
        ),
    ]
