# Generated by Django 4.2.1 on 2023-07-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_burger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burger",
            name="priceL",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="burger",
            name="priceM",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="priceL",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="priceM",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
