# Generated by Django 4.2.1 on 2023-07-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_rice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                (
                    "size",
                    models.CharField(
                        choices=[("M", "Medium"), ("L", "Large")], max_length=1
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(blank=True, upload_to="product_images/")),
            ],
        ),
    ]
